from flashtext import KeywordProcessor

# lists and dictionaries of all the keywords/labels/tags

# immigration status
immstatus_list = [    
    'Business and Commercial work permits',
    'Child Student',
    'Global talent',
    'immigration status',
    'Innovator',
    'International Graduates Scheme',
    'non-visa nationals',
    'Representative of an Overseas Business',
    'Science and Engineering Graduate Scheme',
    'Start-up',
    'Student',
    'Temporary Worker',
    'Tier 1 (General)',
    'Tier 2 (General)',
    'Tier 4 (General)',
    'visa nationals',
    'Youth Mobility Scheme'
]

    # company type
comptype_list = [
    'Branch Office of an Overseas Company',
    'Charity',
    'Co Inc under the Industrial & Provident Societies Act 1968',
    'Company',
    'Company Limited by Guarantee',
    'Incorporated by Royal Charter',
    'Limited Liability Partnership',
    'Limited Partnership',
    'Private Individual',
    'Public Limited Company',
    'Representative Office of an Overseas Company',
    'Sole Trader',
    'Unlimited Company'
]

# regulatory body
regbody_list = [
    'Care Quality Commission',
    'Financial Conduct Authority',
    'General Dental Council',
    'General Medical Council',
    'Ofsted',
    'Prudential Regulation Authority'
]

# region
region_list = [    
    'Commonwealth',
    'EEA',
    'Isle of Man'
    'non-EEA',
    'Nothern Cyprus',
    'refugee',
    'region',
    'Sovereign Base Areas in Cyprus',
    'stateless',
    'Ussr',
    'Yugoslavia'
]

# for dropdown menu: list of country names 
# used by GeoText, taken from https://www.geonames.org/countries/
region_list_for_dropdown = [    
 'Commonwealth',
 'non-EEA',
 'refugee',
 'region',
 'Sovereign Base Areas in Cyprus',
 'stateless',
 'Guernsey',
 'Isle of Man',
 'Jersey',
 'Afghanistan',
 'Åland',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'The Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire, Sint Eustatius, and Saba',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Indian Ocean Territory',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Christmas Island',
 'Cocos [Keeling] Islands',
 'Colombia',
 'Comoros',
 'Congo Republic',
 'DR Congo',
 'Cook Islands',
 'Costa Rica',
 'Ivory Coast',
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Nothern Cyprus',
 'Czechia',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Falkland Islands',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'French Southern Territories',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'North Korea',
 'South Korea',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macau',
 'North Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Norfolk Island',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Barthélemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'São Tomé and Príncipe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Georgia and South Sandwich Islands',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'United Republic of Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Nations',
 'United Nations Agency',
 'United States Minor Outlying Islands',
 'United States of America',
 'Uruguay',
 'U.S. Minor Outlying Islands',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'U.S. Virgin Islands',
 'British Virgin Islands',
 'Wallis and Futuna',
 'Western Sahara',
 'Yemen',
 'Yugoslavia',
 'Zambia',
 'Zimbabwe',
 'Ussr',
 'Svalbard and Jan Mayen Islands',
 'Pitcairn Islands',
 'Kosovo',
 'Bouvet Island',
 'Heard Island and Mcdonald Islands',
]

# company body
compbody_list =[
    'Company body',
    'Franchise',
    'Group of Branches',
    'Single body',
    'UK listed body',
    'UK recognised body',
    'United Kingdom branch'
]

# relation
relation_list = [
    'adoption',
    'dependent relative',
    'family',
    'husband',
    'married',
    'partner',
    'relationship',
    'spouse',
    'unmarried',
    'wife'
]

# position
position_list =[
    'Agent',
    'Director',
    'HR',
    'Recruiter'
]

# role
role_list = [
    'Authorising Officer',
    'Key Contact',
    'Level 1 User',
    'Level 2'
]

    # education
education_list = [
    'Bachelor`s degree',
    'Doctoral',
    'Education',
    'Education Providers',
    'Embedded College offering Pathway Courses',
    'Foundation degree',
    'higher education provider',
    'Honorary degrees',
    'Independent School',
    'MBA',
    'Master`s degree',
    'non-maintained special school',
    'Pathway Course',
    'PhD',
    'Post Graduate Qualification',
    'Postgraduate certificates and diplomas (except PGCE/PGDE)',
    'Professional qualifications (whether or not they are of an equivalent level) that are not degree',
    'primary degree',
    'Qualifications awarded in the UK by overseas awarding bodies',
    'Qualifications undertaken solely at an overseas campus of UK institutions', 
    'recent graduate',
    'state-funded academy',
    'state-funded school'
]

# skill level
skill_level_list = [
    'RQF level 3',
    'RQF level 4',
    'RQF level 6',
    'skill level'
]

# professions
professions_list = [
    'contractual service suppliers',
    'independent professionals',
    'midwives',
    'nurses'
]

# general
general_list = [    
     'A (premium)',
     'A (SME+)',
     'A-rating',
     'age',
     'application',
     'authorising officer',
     'B-rating',
     'bankruptcy',
     'bona fide private education institution',
     'branch',
     'caseworker',
     'Certificate of Sponsorship',
     'certificates of sponsorship',
     'Charge',
     'Charity workers',
     'coaches',
     'company voluntary arrangement',
     'compliance',
     'conviction',
     'convictions and civil penalties',
     'CoS',
     'Creative and sporting',
     'criteria',
     'curtailment',
     'CVA',
     'date',
     'degree language',
     'diplomat',
     'documents',
     'duration',
     'duties',
     'Earn',
     'eligible',
     'Employers',
     'employment agency',
     'employment level',
     'endorsement',
     'entry clearance',
     'exchange',
     'expire',
     'fee',
     'financial requirement',
     'full refund',
     'GAE scheme',
     'genuine vacancy',
     'Government Authorised Exchange',
     'Graduate Trainee',
     'guidance',
     'Health and Care Visasport',
     'highly skilled',
     'Home Office',
     'human resource systems',
     'humanitarian protection',
     'independent',
     'insolvency',
     'International agreement',
     'key contact',
     'Long-term Staff',
     'merge',
     'migrant compliance',
     'missionary',
     'notification',
     'office holder',
     'overarching body',
     'partial refund',
     'Pay',
     'permitted paid engagements',
     'points',
     'points-based',
     'premium customer service',
     'premium sponsor',
     'priority change of circumstances service',
     'professional',
     'protection claim',
     'Rating',
     'refunds',
     'relevant offence',
     'Religious workers',
     'reporting duties',
     'representative',
     'requirement',
     'Restrictions',
     'right to reside',
     'salary',
     'scoring system',
     'Seasonal workers',
     'settled worker',
     'skill',
     'skilled work',
     'sponsor',
     'sposor duties',
     'sponsor licence number',
     'Sponsor Organization',
     'sponsor register',
     'sponsored migrant',
     'sponsorship',
     'sponsorship action plan',
     'sponsorship obligations',
     'sportspeople',
     'suitability criteria',
     'suitable',
     'supporting documents',
     'takeover',
     'temporary work',
     'third-party organisation',
     'time allowed',
     'transit visitor',
     'UK-based representative',
     'UKVI',
     'virtual business',
     'visa',
     'visa waiver',
     'voluntary fieldwork'
]

        
# dictionaries of keywords

# immigration status
immstatus_dict = {
'Tier 2 (Intra-Company Transfer): Established Staff' : ['Established Staff'],
'Tier 2 (Intra-Company Transfer): Graduate Trainee' : ['Graduate Trainee'],
'Tier 2 (Intra-Company Transfer): Long Term staff' : ['Long Term staff'],
'Tier 2 (Intra-Company Transfer): Short Term staff' : ['Short Term staff'],
'Tier 2 (Intra-Company Transfer): Skills Transfer' : ['Skills Transfer'],
'Tier 2 (Minister of Religion)' : ['Minister of Religion'],
'Tier 2 (Sportsperson)'  : ['Sportsperson'],
'Tier 1 (Entrepreneur)' : ['Enterpreneur'],
'Tier 1 (Exceptional Talent)' : ['Exceptional Talent'],
'Tier 1 (Graduate Entrepreneur)' : ['Graduate Entrepreneur'],
'Tier 1 (Investor)' : ['Investor'],
'Representative of an Overseas Newspaper, News Agency or Broadcaster': ['Overseas Newspaper', 'News Agency', 'Broadcaster'],
'Tier 1' : ['Tier 1', 'Tiers 1'],
'Tier 2' : ['Tier 2', 'Tiers 2', 'and 2', 'or 2'],
'Tier 4' : ['Tier 4', 'Tiers 4', 'and 4', 'or 4'],
'Tier 5' : ['Tier 5', 'Tiers 5', 'and 5', 'or 5']
}
 
# region    
region_dict = {
'EEA' : ['European Economic Area'],
'EU' : ['European Union', 'EU'],
'UK regions' : ['England', 'Northern Ireland', 'Scotland', 'Wales'],
'Channel Islands' : ['Channel Islands','Guernsey', 'Jersey'],
'Common Travel Area' : ['Common Travel Area', 'CTA'],
'British Overseas Territories' : [
    'British overseas territories', 'Anguilla','Bermuda', 'British Antarctic Territory', 'British Indian Ocean Territory',
    'British Virgin Islands', 'Cayman Islands', 'Falkland Islands', 'Gibraltar', 'Montserrat',
    'Pitcairn', 'Saint Helena', 'Ascension', 'Tristan da Cunha', 'South Georgia', 'Akrotiri', 
    'Dhekelia', 'Turks and Caicos Islands'],
'Majority English Speaking Countries' : [
    'Antigua and Barbuda','Australia','Bahamas','Barbados','Belize','Canada','Dominica','Grenada','Guyana',
    'Jamaica','New Zealand','Ireland', 'St Kitts and Nevis','St Lucia','St Vincent and the Grenadines',
    'Trinidad and Tobago','USA', 'United States']
}
    
# company type
comptype_dict ={
'Central/local Gov. Dept; Body; Quango, Agency Public Body' : [
    'Central Gov. Dept.', 'Central Government Department',
    'Local Gov. Dept.', 'Central Government Department',
    'Quango', 'Agency Public Body'],
'Hotel and/or Catering Establishment' : ['Hotel Establishment', 'Catering Establishment'],
'Private Limited Company/ Limited Liability Company' : ['Private Limited Company' 'Limited Liability Company'],
'Religious and/or Faith Body' : ['Religious Body', 'Faith Body'],
'Overseas Gov.Int.Organisation, Diplomatic mission' : [
    'Overseas Gov. Int. Organisation', 
    'Overseas Gov.Int.Organisation', 'Diplomatic mission']
}

# company body
compbody_dict = {
'Head office or registered/trading name' : ['Head office', 'registered name', 'trading name'],
'Head Office and all United Kingdom branches' : ['all United Kingdom branches'],
'Subsidiary of a parent company' : ['Subsidiary'],
'Parent company with subsidiaries' : ['Parent company']
}

# relation
relation_dict = {
'child' : ['child', 'children'],
'close relative' : ['close relative', 'close relatives'],
'grandparent' : ['grandparent', 'grandparents'],
'parent' : ['parent', 'parents']
}

# SOC
soc_dict = {
'SOC' : ['Standard Occupational Classification' , 'SOC']
}

# general
general_dict = {
'language requirements' :['language requirements', 'language requirement'],
'sponsor rating' :['sponsor rating', 'sponsor ratings', 'rating sponsors', 'licence rating'],
'SMS' : ['sponsorship management system', 'SMS'],
'top-up charge' : ['top-up charge', 'top-up charges', '‘top-up’ charge', '‘top-up’ charges']
}

# list of needed records

needed_records_list =[
    'accreditation',
    'agreement',
    'annual report',
    'Business premises ownership',
    'certificate',
    'certified copy',
    'confirmation',
    'confirmation of registration',
    'Criminal Record',
    'documentation',
    'evidence',
    'explanation',
    'fire risk assessment',
    'Franchise Agreement',
    'Hierarchy chart',
    'Lease Agreement',
    'letter',
    'licence',
    'online visa application form',
    'overseas accreditation',
    'proof of lease',
    'proof of ownership',
    'proof',
    'record',
    'report',
    'school number',
    'Scottish Executive Education Department code',
    'Stock Exchange listing',
    'Tax Reference Number',
    'tax return',
    'track record of compliance',
    'written record'
]

# dictionary of needed records

needed_records_dict={
'Audited annual accounts': ['annual account', 'annual accounts'],
'Employer’s liability insurance cover': ['employer’s liability','insurance cover'],
'Certificate of VAT registration': ['VAT registration'],
'Company Tax Return CT620': ['CT620'],
'Company Tax Return CT600': ['CT600'],
'Company Tax Return CT603': ['CT603'],
'Copies of advertisements' : ['advertisment', 'advertisments'],
'Complete list of Candidates and their assessment' : ['list of candidates'],
'Corporate/Business Bank Statement' : ['bank statement', 'bank statements'],
'Latest submitted accounts': ['submitted account', 'submitted accounts'],
'PAYE & National Insurance registration': ['Insurance registration','PAYE registration'],
'proof of listing' : ['proof of listing', 'proof of your listing']
}

# list of referencial keywords

reference_list = [
# ----- pdfs ------
 'Policy Guidance',
 'Guidance for Sponsors', 
 'calculating continuous period',
 'English language requirements',
 'Temporary Worker of the Points Based System',
 'Nationality: good character requirement',
 'Guide AN',
 'Nationality policy',
 'Immigration Offences'
 #---------
 'Annex 1',
 'Annex 2',
 'Annex 3',
 'Annex 4',
 'Annex 5',
 'Annex 6',
 'Annex 7',
 'Annex 8',
 'Annex 9',   
 'Approved Destination Status Agreement with China',
 'Booklet AN',
 'Charities Act 2011 for England & Wales',
 'Charities and Trustee Investment (Scotland) Act 2005',
 'Charities Act (Northern Ireland) 2008',
 'Civil Partnership Act 2004',
 'Council Tax Reduction (Scotland) Regulations 2012',
 'Council Tax Reduction (State Pension Credit) (Scotland) Regulations 2012',
 'European Communities Act 1972',
 'European Union (Accessions) Act 2006',
 'European Union (Croatian Accession and Irish Protocol) Act 2013',
 'Health Service (Wales) Act 2006',
 'Health and Social Care (Reform) Act (Northern Ireland) 2009',
 'Housing (Northern Ireland) Order 1988',
 'Housing (Scotland) Act 1987',
 'Housing Act 1985',
 'Human Rights Convention',
 'Immigration (European Economic Area) Regulations 2016',
 'Immigration Act 1971',
 'Immigration Act 2014',
 'Immigration and Asylum Act 1999',
 'Immigration, Asylum and Nationality Act 2006',
 'Immigration Skills Charge calculator',
 'Local Government Finance Act 1992',
 'Localism Act 2011',
 'Marriage (Prohibited Degrees of Relationship) Act 1986',
 'Marriage Act 1949',
 'National Health Service (Charges to Overseas Visitors) (Scotland) Regulations 1989',
 'National Health Service (Charges to Overseas Visitors) Regulations 1989',
 'National Health Service (Charges to Overseas Visitors) Regulations 2015',
 'National Health Service (Scotland) Act 1978',
 'National Health Service Act 2006',
 'Nationality, Immigration and Asylum Act 2002',
 'Provision of Health Services to Persons Not Ordinarily Resident Regulations (Northern Ireland) 2015',
 'Refugee Convention',
 'Refugee or Person in Need of International Protection (Qualification) Regulation 2006',
 'Rehabilitation of Offenders Act 1974',
 'relevant NHS regulations',
 'Right to rent scheme',
 'Tax Credits Act 2002',
 'the 1993 Act',
 'the 1996 Act',
 'the 2006 EEA Regulations',
 'the Immigration Acts',
 'UK Borders Act 2007',
 'Welfare Funds (Scotland) Act 2015',
 'Welfare Reform (Northern Ireland) Order 2015',
 'https://www.gov.uk/government/publications/victims-of-trafficking-guidance-for-competent-bodies'
]

# SOC titles
soc_title_list=["Business, research and administrative professionals n.e.c.", "National government administrative occupations", "Public services associate professionals", "Non-commissioned officers and other ranks", "Marine and waterways transport operatives", "Professional/Chartered company secretaries", "Elected officers and representatives", "Local government administrative occupations", "Energy plant operatives", "Clergy", "Construction and building trades n.e.c.", "Library clerks and assistants", "Musicians", "Chartered and certified accountants", "Book-keepers, payroll managers and wages clerks", "IT business analysts, architects and systems designers", "Taxation experts", "Sports and leisure assistants", "Legal professionals n.e.c.", "Quality assurance and regulatory professionals", "Cleaners and domestics", "Elementary process plant occupations n.e.c.", "Chemical and related process operatives", "Engineering professionals n.e.c.", "Actors, entertainers and presenters", "Actuaries, economists and statisticians", "Therapy professionals n.e.c.", "Estimators, valuers and assessors", "Legal associate professionals", "Metal working production and maintenance fitters", "Precision instrument makers and repairers", "Paper and wood machine operatives", "Plant and machine operatives n.e.c.", "Electrical and electronic trades n.e.c.", "Vehicle technicians, mechanics and electricians", "Routine inspectors and testers", "Officers in armed forces", "Financial administrative occupations n.e.c.", "Other administrative occupations n.e.c.", "Officers of non-governmental organisations", "Welfare and housing associate professionals n.e.c.", "Pensions and insurance clerks and assistants", "Medical secretaries", "Other educational professionals n.e.c", "Business associate professionals n.e.c.", "Company secretaries and administrators", "Records clerks and assistants", "IT operations technicians", "Buyers and procurement officers", "Sales administrators", "Credit controllers", "Human resources administrative occupations", "Data entry administrators", "Database administrators and web content technicians", "IT user support technicians", "Transport and distribution clerks and assistants", "Business sales executives", "Financial and accounting technicians", "Undertakers, mortuary and crematorium assistants", "Stock control clerks and assistants", "Brokers", "Legal secretaries", "School secretaries", "Project support officers", "Customer service occupations n.e.c.", "Travel agents", "CAD, drawing and architectural technicians", "Marketing associate professionals", "Education advisers and school inspectors", "Engineering technicians", "Biological scientists", "Arts officers, producers and directors", "Bank and post office clerks", "Beauticians and related occupations", "Management consultants and business analysts", "Other vocational and industrial trainers", "Careers advisers and vocational guidance specialists", "Catering and bar managers", "Call and contact centre occupations", "Conservation professionals", "Inspectors of standards and regulations", "Welfare professionals n.e.c.", "Retail cashiers and check-out operators", "Shelf fillers", "Sales and retail assistants", "Counsellors", "Health associate professionals n.e.c.", "Human resources and industrial relations officers", "Health and safety managers and officers", "Clothing, fashion and accessories designers", "Finance and investment analysts and advisers", "Physical scientists", "Other health professionals n.e.c.", "Other nursing professionals", "Pharmacy and optical dispensing assistants", "Plumbers & heating and ventilating installers and repairers", "Housing officers", "Authors, writers and translators", "Customer service supervisors", "Generalist medical practitioners", "Sales related occupations n.e.c.", "Vehicle and parts salespersons and advisers", "Chartered architectural technologists, planning officers and consultants", "Public relations professionals", "Pharmacists", "Fire service officers (watch manager and below)", "Production and process engineers", "Telephone salespersons", "Natural and social science professionals n.e.c.", "Protective service associate professionals n.e.c.", "Receptionists", "Child and early years officers", "Barristers and judges", "Glass and ceramics makers, decorators and finishers", "Collector salespersons and credit agents", "Managers and directors in the creative industries", "Production managers and directors in construction", "Debt, rent and other cash collectors", "Production managers and directors in mining and energy", "Delivery drivers and couriers", "Parking and civil enforcement occupations", "Estate agents and auctioneers", "Importers and exporters", "Farmers", "Air travel assistants", "Security guards and related occupations", "Shopkeepers and owners - retail and wholesale", "Air transport operatives", "Sports coaches, instructors and officials", "Insurance underwriters", "Care workers and home carers", "Laboratory technicians", "Nursing auxiliaries and assistants", "Teaching assistants", "Metal making and treating process operatives", "Mining and quarry workers and related operatives", "Assemblers (electrical and electronic products)", "Rail transport operatives", "Social workers", "Textile process operatives", "Chief executives and senior officials", "Ambulance staff (excluding paramedics)", "Specialist medical practitioners", "Programmers and software development professionals", "Merchandisers", "Chemical scientists", "Data analysts", "Cyber security professionals", "Quality control and planning engineers", "Business and related research professionals", "Biochemists and biomedical scientists", "Social and humanities scientists", "Information technology professionals n.e.c.", "IT network professionals", "IT quality and testing professionals", "Quality assurance technicians", "Weighers, graders and sorters", "Building and civil engineering technicians", "Graphic and multimedia designers", "Artists", "Process operatives n.e.c.", "Communication operators", "Agricultural and fishing trades n.e.c.", "Vehicle paint technicians", "Assemblers and routine operatives n.e.c.", "Elementary construction occupations n.e.c.", "Animal care services occupations n.e.c.", "Bricklayers", "Architects", "Mechanical engineers", "Archivists and curators", "Police officers (sergeant and below)", "Complementary health associate professionals", "Florists", "Painters and decorators", "Bakers and flour confectioners", "Dancers and choreographers", "Visual merchandisers and related occupations", "Design occupations n.e.c.", "Pre-press technicians", "Photographers, audio-visual and broadcasting equipment operators", "Kitchen and catering assistants", "Other elementary services occupations n.e.c.", "Hairdressers and barbers", "Other skilled trades n.e.c.", "Construction operatives n.e.c.", "Road construction operatives", "Assemblers (vehicles and metal goods)", "Metal plate workers, smiths, moulders and related occupations", "Print finishing and binding workers", "Footwear and leather working trades", "Warehouse operatives", "Youth and community workers", "Tailors and dressmakers", "Leisure and theme park attendants", "Elementary storage occupations n.e.c.", "Food, drink and tobacco process operatives", "Bar staff", "Market and street traders and assistants", "Packers, bottlers, canners and fillers", "Launderers, dry cleaners and pressers", "Butchers", "Early education and childcare assistants", "Senior care workers", "Caretakers", "Leisure and travel service occupations n.e.c.", "Playworkers", "Dental nurses", "Houseparents and residential wardens", "Waiters and waitresses", "Delivery operatives", "Other drivers and transport operatives n.e.c.", "Interior designers", "Web design professionals", "Personal assistants and other secretaries", "Water and sewerage plant operatives", "Electrical and electronics technicians", "Conference and exhibition managers and organisers", "Science, engineering and production technicians n.e.c.", "Plastics process operatives", "Postal workers, mail sorters and messengers", "Fishing and other elementary agriculture occupations n.e.c.", "Farm workers", "Fishmongers and poultry dressers", "Tyre, exhaust and windscreen fitters", "Horticultural trades", "Gardeners and landscape gardeners", "Printing machine assistants", "Elementary administration occupations n.e.c.", "Roundspersons and van salespersons", "Educational support assistants", "Elementary sales occupations n.e.c.", "Teaching professionals n.e.c.", "Rail travel assistants", "School midday and crossing patrol occupations", "Textiles, garments and related trades n.e.c.", "Care escorts", "Chartered surveyors", "Other psychologists", "Market research interviewers", "Electrical engineers", "Electronics engineers", "Other researchers, unspecified discipline", "Sewing machinists", "Sales supervisors - retail and wholesale", "Office supervisors", "Aircraft pilots and air traffic controllers", "Coffee shop workers", "Quantity surveyors", "Higher level teaching assistants", "Higher education teaching professionals", "Vehicle valeters and cleaners", "Welding trades", "Solicitors and lawyers", "Medical and dental technicians", "Sports players", "Elementary cleaning occupations n.e.c.", "Metal working machine operatives", "Telephonists", "Crane drivers", "Groundsmen and greenkeepers", "Refuse and salvage occupations", "Electricians and electrical fitters", "Street cleaners", "Forestry and related workers", "Mobile machine drivers and operatives n.e.c.", "Housekeepers and related occupations", "Nannies and au pairs", "Metal machining setters and setter-operators", "Prison service officers (below principal officer)", "Financial managers and directors", "Financial accounts managers", "Stonemasons and related trades", "Bar and catering supervisors",
"Glaziers, window fabricators and fitters", "Vehicle body builders and repairers", "Sheet metal workers",
"Furniture makers and other craft woodworkers", "Chefs", "Fitness and wellbeing instructors", "Production, factory and assembly supervisors", "Printers", "Boat and ship builders and repairers", "Waste disposal and environmental services managers", "Floorers and wall tilers", "Carpenters and joiners", "Hotel and accommodation managers and proprietors", "Bus and coach drivers", "Cleaning and housekeeping managers and supervisors", "Taxi and cab drivers and chauffeurs", "Ship and hovercraft officers", "Environment professionals", "Senior officers in fire, ambulance, prison and related services", "Managers in transport and distribution", "Childminders", "Large goods vehicle drivers", "Roofers, roof tilers and slaters", "Plasterers", "Pest control officers", "Education managers", "Construction and building trades supervisors", "Podiatrists", "Industrial cleaning process occupations", "Window cleaners", "Functional managers and directors n.e.c.", "Typists and related keyboard occupations", "Leisure and sports managers", "Construction project managers and related professionals", "Steel erectors", "Road transport drivers n.e.c.", "Newspaper and periodical journalists and reporters", "Directors in logistics, warehousing and transport", "Senior police officers", "Health services and public health managers and directors", "Social services managers and directors", "Telecoms and related network installers and repairers", "Rail construction and maintenance operatives", "Advertising accounts managers and creative directors", "Dental practitioners", "Civil engineers", "Specialist nurses", "Nursery education teaching professionals", "Veterinarians", "Groundworkers", "Sales accounts and business development managers", "Cooks", "Planning, process and production technicians", "Skilled metal, electrical and electronic trades supervisors", "Information technology trainers", "Special needs education teaching professionals", "Business and financial project management professionals", "Tool makers, tool fitters and markers-out", "Psychotherapists and cognitive behaviour therapists", "Upholsterers", "Electrical service and maintenance mechanics and repairers", "Restaurant and catering establishment managers and proprietors", "Garage managers and proprietors", "Aerospace engineers", "Property, housing and estate managers", "Marketing, sales and advertising directors", "Purchasing managers and directors", "Charitable organisation managers and directors", "Public relations and communications directors", "Production managers and directors in manufacturing", "Human resource managers and directors", "Newspaper and periodical editors", "Managers and directors in retail and wholesale", "Managers and proprietors in other services n.e.c.", "Information technology directors", "Early education and childcare services proprietors", "Research and development (R&D) managers", "Directors in consultancy services", "Further education teaching professionals", "Secondary education teaching professionals", "Aircraft maintenance and related trades", "Dispensing opticians", "Train and tram drivers", "Fork-lift truck drivers", "Driving instructors", "Early education and childcare practitioners", "TV, video and audio servicers and repairers", "Physiotherapists", "Security system installers and repairers", "Computer system and equipment installers and servicers", "Air-conditioning and refrigeration installers and repairers", "Rail and rolling stock builders and repairers", "Pipe fitters", "Engineering project managers and project engineers", "Scaffolders, stagers and riggers", "Elementary storage supervisors", "Primary education teaching professionals", "Head teachers and principals", "Office managers", "Customer service managers", "Publicans and managers of licensed premises", "Environmental health professionals", "Probation officers", "Exam invigilators", "Bed and breakfast and guest house owners and proprietors", "IT project managers", "Midwifery nurses", "Teachers of English as a foreign language", "Librarians", "Managers and proprietors in agriculture and horticulture", "Marketing and commercial managers", "Managers in storage and warehousing", "IT managers", "Travel agency managers and proprietors", "Hairdressing and beauty salon managers and proprietors", "Betting shop and gambling establishment managers", "Hire services managers and proprietors", "Early education and childcare services managers", "Residential, day and domiciliary care managers and proprietors", "Managers in logistics", "Health care practice managers", "Managers and proprietors in forestry, fishing and related services", "Community nurses", "Veterinary nurses", "Children`s nurses", "Mental health nurses", "Nurse practitioners", "Police community support officers", "Finance officers", "Youth work professionals", "Medical radiographers", "Ophthalmic opticians", "Paramedics", "Hospital porters", "Clinical psychologists", "Pharmaceutical technicians", "Speech and language therapists", "Occupational therapists"]

# SOC codes
soc_codes_list=[
 '1115',
 '1116',
 '1121',
 '1122',
 '1123',
 '1131',
 '1132',
 '1133',
 '1134',
 '1135',
 '1136',
 '1139',
 '1150',
 '1161',
 '1162',
 '1171',
 '1172',
 '1173',
 '1181',
 '1184',
 '1190',
 '1211',
 '1213',
 '1221',
 '1223',
 '1224',
 '1225',
 '1226',
 '1241',
 '1242',
 '1251',
 '1252',
 '1253',
 '1254',
 '1255',
 '1259',
 '2111',
 '2112',
 '2113',
 '2114',
 '2119',
 '2121',
 '2122',
 '2123',
 '2124',
 '2126',
 '2127',
 '2129',
 '2133',
 '2134',
 '2135',
 '2136',
 '2137',
 '2139',
 '2141',
 '2142',
 '2150',
 '2211',
 '2212',
 '2213',
 '2214',
 '2215',
 '2216',
 '2217',
 '2218',
 '2219',
 '2221',
 '2222',
 '2223',
 '2229',
 '2231',
 '2232',
 '2311',
 '2312',
 '2314',
 '2315',
 '2316',
 '2317',
 '2318',
 '2319',
 '2412',
 '2413',
 '2419',
 '2421',
 '2423',
 '2424',
 '2425',
 '2426',
 '2429',
 '2431',
 '2432',
 '2433',
 '2434',
 '2435',
 '2436',
 '2442',
 '2443',
 '2444',
 '2449',
 '2451',
 '2452',
 '2461',
 '2462',
 '2463',
 '2471',
 '2472',
 '2473',
 '3111',
 '3112',
 '3113',
 '3114',
 '3115',
 '3116',
 '3119',
 '3121',
 '3122',
 '3131',
 '3132',
 '3213',
 '3216',
 '3217',
 '3218',
 '3219',
 '3231',
 '3233',
 '3234',
 '3235',
 '3239',
 '3311',
 '3312',
 '3313',
 '3314',
 '3315',
 '3319',
 '3411',
 '3412',
 '3413',
 '3414',
 '3415',
 '3416',
 '3417',
 '3421',
 '3422',
 '3441',
 '3442',
 '3443',
 '3511',
 '3512',
 '3513',
 '3520',
 '3531',
 '3532',
 '3533',
 '3534',
 '3535',
 '3536',
 '3537',
 '3538',
 '3539',
 '3541',
 '3542',
 '3543',
 '3544',
 '3545',
 '3546',
 '3550',
 '3561',
 '3562',
 '3563',
 '3564',
 '3565',
 '3567',
 '4112',
 '4113',
 '4114',
 '4121',
 '4122',
 '4123',
 '4124',
 '4129',
 '4131',
 '4132',
 '4133',
 '4134',
 '4135',
 '4138',
 '4151',
 '4159',
 '4161',
 '4162',
 '4211',
 '4212',
 '4213',
 '4214',
 '4215',
 '4216',
 '4217',
 '5111',
 '5112',
 '5113',
 '5114',
 '5119',
 '5211',
 '5212',
 '5213',
 '5214',
 '5215',
 '5216',
 '5221',
 '5222',
 '5223',
 '5224',
 '5225',
 '5231',
 '5232',
 '5234',
 '5235',
 '5236',
 '5237',
 '5241',
 '5242',
 '5244',
 '5245',
 '5249',
 '5250',
 '5311',
 '5312',
 '5313',
 '5314',
 '5315',
 '5316',
 '5319',
 '5321',
 '5322',
 '5323',
 '5330',
 '5411',
 '5412',
 '5413',
 '5414',
 '5419',
 '5421',
 '5422',
 '5423',
 '5431',
 '5432',
 '5433',
 '5434',
 '5435',
 '5436',
 '5441',
 '5442',
 '5443',
 '5449',
 '6121',
 '6122',
 '6123',
 '6125',
 '6126',
 '6131',
 '6132',
 '6139',
 '6141',
 '6142',
 '6143',
 '6144',
 '6145',
 '6146',
 '6147',
 '6148',
 '6211',
 '6212',
 '6214',
 '6215',
 '6219',
 '6221',
 '6222',
 '6231',
 '6232',
 '6240',
 '7111',
 '7112',
 '7113',
 '7114',
 '7115',
 '7121',
 '7122',
 '7123',
 '7124',
 '7125',
 '7129',
 '7130',
 '7211',
 '7213',
 '7214',
 '7215',
 '7219',
 '7220',
 '8111',
 '8112',
 '8113',
 '8114',
 '8115',
 '8116',
 '8117',
 '8118',
 '8119',
 '8121',
 '8122',
 '8123',
 '8124',
 '8125',
 '8126',
 '8127',
 '8129',
 '8131',
 '8132',
 '8133',
 '8134',
 '8135',
 '8137',
 '8139',
 '8141',
 '8142',
 '8143',
 '8149',
 '8211',
 '8212',
 '8213',
 '8214',
 '8215',
 '8221',
 '8222',
 '8223',
 '8229',
 '8231',
 '8232',
 '8233',
 '8234',
 '8239',
 '9111',
 '9112',
 '9119',
 '9120',
 '9132',
 '9134',
 '9139',
 '9211',
 '9219',
 '9231',
 '9232',
 '9233',
 '9234',
 '9235',
 '9236',
 '9239',
 '9241',
 '9242',
 '9244',
 '9249',
 '9251',
 '9259',
 '9260',
 '9271',
 '9272',
 '9273',
 '9274',
 '9275',
 '9279']



# all keyword lists except needed records and references in one list
keyword_list = (immstatus_list + comptype_list + regbody_list + region_list 
                + compbody_list + relation_list + position_list + role_list
                + education_list + skill_level_list + professions_list
                + general_list + soc_title_list + soc_codes_list)



# combined keyword dictionary
keyword_dict = {**immstatus_dict, **region_dict, **comptype_dict, **compbody_dict, **relation_dict, **soc_dict, **general_dict}

# dictionary for dropdown menu
dropdown_dict = {
    "immigration status" : sorted(immstatus_list + list(immstatus_dict.keys()), key=str.casefold),
    "region" : sorted(region_list_for_dropdown + list(region_dict.keys()), key=str.casefold),
    "company type" : sorted(comptype_list, key=str.casefold),
    "company body" : sorted(compbody_list + list(compbody_dict.keys()), key=str.casefold),
    "regulatory body" : sorted(regbody_list, key=str.casefold),
    "education" : sorted(education_list, key=str.casefold),
    "skill level" : sorted(skill_level_list, key=str.casefold),
    "relation" : sorted(relation_list + list(relation_dict.keys()), key=str.casefold),
    "position" : sorted(position_list, key=str.casefold),
    "role" : sorted(role_list, key=str.casefold),
    "profession": sorted(professions_list, key=str.casefold),
    "SOC codes" : sorted(list(soc_dict.keys()) + soc_codes_list, key=str.casefold),
    "SOC titles" : sorted(soc_title_list, key=str.casefold),
    "general" : sorted(general_list + list(general_dict.keys()), key=str.casefold)
}


# Flashtext's keyword processors
keyword_processor_ref = KeywordProcessor(case_sensitive=False)
keyword_processor_all = KeywordProcessor(case_sensitive=False)
keyword_processor_rec = KeywordProcessor(case_sensitive=False)

keyword_processor_ref.add_keywords_from_list(reference_list)
keyword_processor_all.add_keywords_from_list(keyword_list)
keyword_processor_all.add_keywords_from_dict(keyword_dict)
keyword_processor_rec.add_keywords_from_list(needed_records_list)
keyword_processor_rec.add_keywords_from_dict(needed_records_dict)

